stages:
  - deploy

Deploy (Staging):
  image: docker
  services:
    - docker:dind
  stage: deploy
  script:
    - docker login -u username -p password
    - docker build -t boilerplate-graphql-api .
    - docker tag boilerplate-graphql-api:latest registry.site.com/boilerplate-graphql-api:latest
    - docker push registry.site.com/boilerplate-graphql-api:latest
  only:
    - staging
